name: Deploy Loan Predictor

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install pandas numpy scikit-learn gradio transformers accelerate

      - name: Run app test
        run: python app.py --help

      - name: Build Docker image
        run: docker build -t loan-predictor .

      - name: Push to DockerHub (optional)
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
        run: |
          echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
          docker tag loan-predictor $DOCKER_USER/loan-predictor:latest
          docker push $DOCKER_USER/loan-predictor:latest
